name: Serverless (release)

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1
  # AWS_DISTRIBUTION_ID: E3O0EETZCXPF32
  # AWS_OAI: ${{ secrets.AWS_OAI }}
  # STAGE: widgets
  # BASE_PATH: /widgets

jobs:
  deploy_serverless:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.19.0
      - name: Install Serverless
        run: npm install -g cdk@1.92.0
      - name: Install Dependecies
        run: yarn install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - name: Deploy Next.js Application
        run: cdk deploy